{
  "theme": "Bubbles",
  "controlStyles[0].target": "taskbar:TaskListLabeledButtonPanel@RunningIndicatorStates > Border",
  "controlStyles[0].styles[0]": "CornerRadius=20",
  "controlStyles[1].target": "Taskbar.TaskListLabeledButtonPanel@CommonStates > Rectangle#RunningIndicator",
  "controlStyles[1].styles[0]": "Width=6",
  "controlStyles[1].styles[1]": "Height=6",
  "controlStyles[1].styles[2]": "RadiusX=20",
  "controlStyles[1].styles[3]": "RadiusY=20",
  "controlStyles[2].target": "Taskbar.TaskbarFrame#TaskbarFrame",
  "controlStyles[2].styles[0]": "Margin=0,0,0,0",
  "controlStyles[2].styles[1]": "Padding=0,0,0,0",
  "controlStyles[2].styles[2]": "Width=Auto",
  "controlStyles[2].styles[3]": "HorizontalAlignment=Center",
  "controlStyles[2].styles[4]": "MaxWidth=MaxContent",
  "controlStyles[3].target": "Rectangle#BackgroundFill",
  "controlStyles[3].styles[0]": "Visibility=Collapsed",
  "controlStyles[4].target": "Rectangle#BackgroundStroke",
  "controlStyles[4].styles[0]": "Visibility=Collapsed",
  "controlStyles[5].target": "Taskbar.TaskbarFrame#TaskbarFrame > Grid#RootGrid",
  "controlStyles[5].styles[0]": "Padding=2,0,2,0",
  "controlStyles[5].styles[1]": "CornerRadius=24",
  "controlStyles[5].styles[2]": "Background:=<AcrylicBrush TintColor=\"{ThemeResource SystemChromeAltHighColor}\" TintOpacity=\"0.8\" FallbackColor=\"{ThemeResource SystemChromeLowColor}\" />"
}
